#!/usr/bin/python3
""" Fetches the https://intranet.hbtn.io/status
"""
import urllib.request as req


if __name__ == "__main__":
    with req.urlopen("https://intranet.hbtn.io/status") as res:
        print(dir(res.read().title))
